// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2Jgiqc8oBvuc48vmwWiosZlmKZFiRnHQ',
    appId: '1:804746525773:web:d6cfff934f6a5f14edb004',
    messagingSenderId: '804746525773',
    projectId: 'cine-tribe',
    authDomain: 'cine-tribe.firebaseapp.com',
    storageBucket: 'cine-tribe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsqJ0R1ykOWTWmIt2su_wvY36OLSY4ECY',
    appId: '1:804746525773:android:da2662c3fa4e1d2fedb004',
    messagingSenderId: '804746525773',
    projectId: 'cine-tribe',
    storageBucket: 'cine-tribe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkCR_oYr3Tmqcgzdt__Ns6CVRexP8bs4c',
    appId: '1:804746525773:ios:393fa4fa91f3ca1eedb004',
    messagingSenderId: '804746525773',
    projectId: 'cine-tribe',
    storageBucket: 'cine-tribe.appspot.com',
    iosClientId: '804746525773-i34ivh5c8b4nthkpdcbddbhjfn0k2qbf.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinetribe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkCR_oYr3Tmqcgzdt__Ns6CVRexP8bs4c',
    appId: '1:804746525773:ios:6040be49483e2d27edb004',
    messagingSenderId: '804746525773',
    projectId: 'cine-tribe',
    storageBucket: 'cine-tribe.appspot.com',
    iosClientId: '804746525773-9ssh0hpkogjokij0rs67ebrag2dee0um.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinetribe.RunnerTests',
  );
}
